import time

time.sleep(3)
print("Well done for hacking into the Macroware administrator account")
time.sleep(3)
print("We now have access to the information of Macroware and where they will be meeting and what they plan to do.")
time.sleep(3)
print("We will get back to you once we have some information on them.")
time.sleep(5)
print("We have gotten some information on Macroware and it says that they plan to rig the elections that are going to come soon.\n")
time.sleep(3)
print("This election is going to be between John Smith and Ted Stevenson")
time.sleep(3)
print("We feel like that Macroware also has part in this election and will do everything to jeoparadise the election, and we also believe that they will rig the elections.")

print("and his account is very secure and it may have 2-step verification and the code will be sent to his personal email.") 
print("it may be difficult to get into the account but there is good news.")
print("The engineers at the FCA have reengineered the Exterminat0r to bypass security and give you hints to how to get into the CEO's account.\n")
print("The Exterminat0r says: ")
print("// The CEO's business email is: BMorrison@Macroware.com")
print("// His password contains his company's name")
print("// and it also contains numbers as well")
print("// it also contains his name as well")
time.sleep(3)
print("// Also, I forgot to mention. That I have been upgraded with a command line and you can do various things")
print("// To get access to the Exterminat0r command line, you type in 'ExterCMD'\n")
