import time

print("\nRemoving system files...")
time.sleep(5)
print("shutting down computer")
time.sleep(3)
print("rebooting computer...")
time.sleep(4)
print("Some system files are missing")
print("Error code: 0x6FFFFAAAE3526")
time.sleep(5)
print("\nFCA: Just, why!")
time.sleep(3)
print("FCA: Why the f*** would you do that?!")
time.sleep(3)
print("FCA: You know what, you're fired!")
time.sleep(3)
print("FCA: You have not only destroyed your computer but you have destroyed every computer on our network!")
print("FCA: In fact, we will have you arrested for treason and misuse of computers.\n\n")
print("narrator: and the hacker has been arrested for treason and now serves a life-time imprisonement\n")
print("Ending 2: fired from job and arrested for treason")
